### ISSUE TITLE
Working on Android now but having error on adding plugin in iOS

### ISSUE THREAD

**Issue by aerialglasgow** [mfdeveloper/cordova-plugin-nativeview#13]
Hi. Thanks for sharing this great plugin. 

I'm getting this error on attempting to install the plugin for iOS, using: 

cordova plugin add cordova-plugin-nativeview --save

Cordova version is 8.0.0 
iOS platform version 4.5.5

##############

`Installing "cordova-plugin-nativeview" for ios
Dependent plugin "es6-promise-plugin" already installed on ios.
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-nativeview': CordovaError: Uh oh!
"/users/main/documents/cordova/nativear01/plugins/cordova-plugin-nativeview/src/ios/InstantiateViewControllerError.m" not found!
    at copyFile (/users/main/documents/cordova/nativear01/platforms/ios/cordova/lib/plugman/pluginHandlers.js:319:36)
    at copyNewFile (/users/main/documents/cordova/nativear01/platforms/ios/cordova/lib/plugman/pluginHandlers.js:348:5)
    at installHelper (/users/main/documents/cordova/nativear01/platforms/ios/cordova/lib/plugman/pluginHandlers.js:269:13)
    at install (/users/main/documents/cordova/nativear01/platforms/ios/cordova/lib/plugman/pluginHandlers.js:35:13)
    at ActionStack.process (/users/main/documents/cordova/nativear01/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/users/main/documents/cordova/nativear01/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/users/main/documents/cordova/nativear01/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at Api.addPlugin (/users/main/documents/cordova/nativear01/platforms/ios/cordova/Api.js:234:10)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
(node:12874) UnhandledPromiseRejectionWarning: CordovaError: Uh oh!
"/users/main/documents/cordova/nativear01/plugins/cordova-plugin-nativeview/src/ios/InstantiateViewControllerError.m" not found!

##############

Am I missing something? 

Thanks
Neill

**Comment by aerialglasgow** [comment]
Thanks Felipe. I will try to install the 0.0.8 version and reply with the result. Again many thanks.
Neill
