### ISSUE TITLE
Error if browser platform is installed

### ISSUE THREAD

**Issue by klemensz** [mfdeveloper/cordova-plugin-nativeview#24]
There is an error thrown if a project has the "browser" platform added in addition to the "android" and "ios" platforms.

This happens when running `cordova prepare ios` for example.

```
TypeError: Cannot read property 'ScrollEnabled' of undefined
    at /my-project/plugins/cordova-plugin-nativeview/scripts/after.prepare.js:235:70
    at arrayEach (/my-project/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/my-project/node_modules/lodash/lodash.js:9344:14)
    at Object.parsePreferences (/my-project/plugins/cordova-plugin-nativeview/scripts/after.prepare.js:233:15)
    at Object.parseConfigXml (/my-project/plugins/cordova-plugin-nativeview/scripts/after.prepare.js:220:18)
    at Object.updatePlatformConfig (/my-project/plugins/cordova-plugin-nativeview/scripts/after.prepare.js:282:35)
    at /my-project/plugins/cordova-plugin-nativeview/scripts/after.prepare.js:381:32
    at arrayEach (/my-project/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/my-project/node_modules/lodash/lodash.js:9344:14)
    at module.exports (/my-project/plugins/cordova-plugin-nativeview/scripts/after.prepare.js:378:11)
```

**Comment by mfdeveloper** [comment]
Hy @klemensz !

I've merged you simple pull request. I will close this issue now, ok?

If I can help you in something else, just tell me :)

**Comment by klemensz** [comment]
OK, thanks!
